apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kubedemo
  name: kubedemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubedemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubedemo
    spec:
      containers:
      - image: gabidockerid/streak
        name: streak
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
  type: ClusterIP
status:
  loadBalancer: {}
