apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: gabidockerid/auth-service-image:1.0.0
          ports:
            - containerPort: 7777
          env:
            - name: spring.profiles.active
              value: kafka
            - name: SERVICE_NAME
              value: auth-service
            - name: HONEYCOMB_METRICS_DATASET
              value: my-metrics
            - name: HONEYCOMB_CONFIG_FILE
              value: honeycomb.properties
            - name: OTEL_SERVICE_NAME
              value: auth-service
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-secret
                  key: honeycomb-api-key
            - name: spring.data.mongodb.username
              valueFrom:
                secretKeyRef:
                  name: auth-mongo-secret
                  key: MONGO_AUTH_USER
            - name: spring.data.mongodb.password
              valueFrom:
                secretKeyRef:
                  name: auth-mongo-secret
                  key: MONGO_AUTH_PASS
            - name: spring.data.mongodb.host
              value: "mongo-auth-service"
            - name: spring.data.mongodb.conn
              value: "mongodb://authserviceuser:authservicepass@mongo-auth-service.default.svc.cluster.local:27017/streak"
              #value: "mongodb+srv://authserviceuser:authservicepass@mongo-auth-service.default.svc.cluster.local:27017/streak"

          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 7777
  type: ClusterIP