# FROM mongo
# EXPOSE 27017
# ARG JAR_FILE=build/libs/*.jar
# COPY ${JAR_FILE} authentication-service.jar
# COPY honeycomb-opentelemetry-javaagent.jar honeycomb-opentelemetry-javaagent.jar
# ENTRYPOINT ["java", "-javaagent:honeycomb-opentelemetry-javaagent.jar", "-Dotel.javaagent.debug=false", "-jar", "authentication-service.jar"]
