apiVersion: apps/v1
kind: Deployment
metadata:
  name: streak-web
  labels:
    app: streak-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streak-web
  template:
    metadata:
      labels:
        app: streak-web
    spec:
      containers:
        - name: streak-web
          image: gabidockerid/streak-web-image:1.0.2
          ports:
            - containerPort: 8888
          env:
            - name: logging.level.org.apache.kafka
              value: DEBUG
            - name: spring.kafka.bootstrap-servers
              value: tcp://kafka-service.kafka.svc.cluster.local:9092
            - name: STREAK_CLIENT_ENDPOINT
              value: http://streak-client:9999/
            - name: SERVICE_NAME
              value: streak-web-service
            - name: HONEYCOMB_METRICS_DATASET
              value: my-metrics
            - name: HONEYCOMB_CONFIG_FILE
              value: honeycomb.properties
            - name: OTEL_SERVICE_NAME
              value: streak-web-service
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-secret
                  key: honeycomb-api-key

          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: streak-web
spec:
  selector:
    app: streak-web
  ports:
    - port: 8888
  type: ClusterIP